products/urls.py
"""Products URLs"""
from django.urls import path, re_path
from . import views


app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    #  path('results.html', views.showlist, name='showlist'),
    path('<int:product_id>', views.detail, name='detail'),
    # path('results.html', views.results, name='index'),
    # re_path(r'^search/$', views.search, name='search'),
    # path('results.html', views.results, name='results'),
]

smile/urls.py
from django.contrib import admin
from django.urls import path, include
import api.models
from . import views


product_resource = api.models.ProductResource()
type_resource = api.models.TypeResource()

urlpatterns = [
    # path('', views.home),
    path('', views.showlist, name='showlist'),
    path('base.html', views.showlist, name='showlist'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('api/', include(product_resource.urls)),
    path('api/', include(type_resource.urls))
]

admin.site.site_header = "Smile! Lookup Admin"
admin.site.site_title = "Smile! Lookup Admin Portal"
admin.site.index_title = "Welcome to Smile! Lookup Portal"

api/models.py
from django.db import models
import tastypie.resources
import products.models
import tastypie.fields


class TypeResource(tastypie.resources.ModelResource):
    class Meta:
        queryset = products.models.Type.objects.all()
        resource_name = 'types'


class ProductResource(tastypie.resources.ModelResource):
    # type = fields.ForeignKey(TypeResource, 'type')
    # types = fields.ToManyField(TypeResource, 'type_set')
    # type = fields.ForeignKey(TypeResource, 'type')
    # type = fields.ToOneField(TypeResource, 'type', full=True)
    type = tastypie.fields.ForeignKey(
        TypeResource, attribute='type', null=True)

    class Meta:
        queryset = products.models.Product.objects.all()
        resource_name = 'products'
        excludes = ['date_created', 'selected_yn']

products/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import django_filters


class Type(models.Model):
    """Type Class"""
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return str(self.name)


class Product(models.Model):
    """Product Class"""
    code = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255, blank=True, null=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    selected_yn = models.BooleanField(default=False, blank=True, null=True)
    date_created = models.DateTimeField(
        default=timezone.now, blank=True, null=True)


class ProductList(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        managed = False
        db_table = 'products_product'


class ProductFilter(django_filters.FilterSet):
    name = django_filters.CharFilter(lookup_expr='icontains')

    class Meta:
        model = Product
        fields = ['name']

api/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
"""Views.py (Product App)"""
from django import apps
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from . models import Product, ProductFilter
from django.template import loader


# Create your views here.

def index(request):
    """Index"""
    f = ProductFilter(
        request.GET, queryset=Product.objects.all().order_by('code'))
    has_filter = any(field in request.GET for field in set(f.get_fields()))

    return render(request, 'products/index.html', {
        'filter': f,
        'has_filter': has_filter
    })


def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'products/detail.html', {'product': product})


# def index(request):
#     """Index"""
#     products = Product.objects.all()
#     return render(request, 'products/index.html', {'products': products})


# def showlist(request):
#         results = Product.objects.all
#         return render(request, "products/results.html", {"showproduct": results})


# def results(request):
#     # | Product.objects.filter(firstname='Tobias').values()
#     mydata = Product.objects.filter(name__startswith='C').values()
#     template = loader.get_template('products/results.html')
#     context = {
#         'products': mydata,
#     }
#     return HttpResponse(template.render(context, request))
    # products = Product.objects.all
    # return render(request, "products/results2.html", {'products': products})

# def search(request):
#     product_list = Product.objects.all()
#     product_filter = ProductFilter(request.GET, queryset=product_list)
#     return render(request, 'products/search/product_list.html', {'filter': product_filter})


# def results(request):
#     product_list = Product.objects.all()
#     product_filter = ProductFilter(request.GET, queryset=product_list)
#     return render(request, 'products/results.html', {'filter': product_filter})


# def results(request):
#     f = ProductFilter(
#         request.GET, queryset=Product.objects.all().order_by('code'))
#     has_filter = any(field in request.GET for field in set(f.get_fields()))

#     return render(request, 'products/results.html', {
#         'filter': f,
#         'has_filter': has_filter
#     })

smile/views.py
from django.shortcuts import render
from products.models import Product
from products.models import ProductList


def home(request):
    return render(request, 'home.html')


def showlist(request):
    results = Product.objects.all
    return render(request, "home.html", {"showproduct": results})

products/templates/products/detail.html
{% extends "base.html" %}
{% block content %}
    <dl>
        <dt>Code</dt>
        <dd>{{product.code}}</dd>
        <dt>Type</dt>
        <dd>{{product.type}}</dd>
        <dt>Name</dt>
        <dd>{{product.name}}</dd>
        <dt>Description</dt>
        <dd>{{product.description}}</dd>
    </dl>
{% endblock %}

products/templates/products/index.html
{% extends "base.html" %}

{% block content %}

{% comment %} <form class="d-flex" role="search">
        <input class="form-control me-2" list="productlist" type="search" placeholder="Search" aria-label="Search">
          <datalist id="productlist">
            {% for results in showproduct %}
                    <option value="{{results.name}}">
            {% endfor %}
          </datalist>
        <button class="btn btn-outline-success" type="submit">Search</button>
</form> {% endcomment %}


  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>
  {% for product in filter %}
    <li>{{ product.name }}</li>
  {% endfor %}
  </ul>
{% endblock %}

    {% comment %} <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Code</th>
                <th>Type</th>
                <th>Name</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>
                        <a href="{% url 'products:detail' product.id %}">{{ product.code}}</a>
                    </td>
                    <td>{{ product.type}}</td>
                    <td>{{ product.name}}</td>
                    <td>{{ product.description}}</td>
                </tr>
            {% endfor %}
            
        </tbody>
    </table>
{% endblock  %} {% endcomment %}

products/templates/products/results.html
{% extends "base.html" %}

{% block content %}

{% comment %} <p>The queryset object:</p>

{{ products }} {% endcomment %}

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Code</th>
                <th>Type</th>
                <th>Name</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>
                        <a href="{% url 'products:detail' product.id %}">{{ product.code}}</a>
                    </td>
                    <td>{{ product.type}}</td>
                    <td>{{ product.name}}</td>
                    <td>{{ product.description}}</td>
                </tr>
            {% endfor %}
            
        </tbody>
    </table>
{% endblock  %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Smile! Lookup App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href=" https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
    
    <nav class="navbar bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand">Smile! Lookup</a>
        <img src="{% static 'images/smiletech.png' %}" alt="Smile Tech Logo" style="width:250px;height:60px;">
        <!--<form class="d-flex" role="search" action="{{ results.html }}" method="post">-->
        
    </div>
    </nav>
    &nbsp;
    <main class="container">
        {% block content %}
        {% endblock  %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'products:index' %}">Products</a>   
{% endblock  %}
